### ISSUE TITLE
not lovelace card(

### ISSUE THREAD

**Issue by molodoy6260** [ad-ha/atw#2]
Added resources to Lovelace configuration

```
resources:
  - url: /hacsfiles/advanced_trading_wallet/lovelace/portfolio-card.js
    type: module
  - url: /hacsfiles/advanced_trading_wallet/lovelace/transaction-card.js
    type: module
  - url: /hacsfiles/advanced_trading_wallet/lovelace/asset-summary-card.js
    type: module
```

but the cards are not visible in the list(
